services:

  postgres:
    image: postgres:17
    container_name: smartflow-postgres
    environment:
      POSTGRES_DB: smartflow
      POSTGRES_USER: smartflow
      POSTGRES_PASSWORD: smartflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: